### ISSUE TITLE
Roadmap to build gdrive clone

### ISSUE THREAD

**Issue by yuito22suto** [yuito22suto/gdrive_clone#3]
- [ ] Project Setup
- [ ] Install Laravel Breeze
- [ ] Email Verification
- [ ] DB Overview, Models & Migrations
- [ ] Explore Intertia Folder Structure
- [ ] Authentication Layout
- [ ] Define Main Routes
- [ ] Create Root Folder On User Registration
- [ ] Creating Folder
- [ ] Save Folder Path
- [ ] Show Files into table
- [ ] Navigate into Second Level of Folders
- [ ] Create Folders Inside Subfolder
- [ ] Implement Breadcrumbs
- [ ] Uploading Files
- [ ] Show Human Readable File size
- [ ] Show File Icons
- [ ] Show File Progress
- [ ] Display Error When File Already Exists
- [ ] Implement Load More
- [ ] Increase max_file_uploads
- [ ] Deleting Files
- [ ] Implement Downloading Files
- [ ] Show Success Notifications
- [ ] Implement Trash
- [ ] Implement Favourites
- [ ] Sharing Files to Others
- [ ] Implement Shared With Me Page
- [ ] Implement Shared By Me Page
- [ ] Searching for Files
- [ ] Connect to AWS S3
- [ ] Download Files from S3
- [ ] Project Deployment & Bug Fixing
